### ISSUE TITLE
Question Related to comment added in the code

### ISSUE THREAD

**Issue by mgelkunchw** [OSGeo/shapelib#10]
In dbfopen.c file we have a function DBFIsValueNULL(), in the comment you have mentioned 
/*
        ** We accept all asterisks or all blanks as NULL
        ** though according to the spec I think it should be all
        ** asterisks.
        */
/* NULL boolean fields have value "?" */

which specification tells that '*' is NULL for numeric and '?' for Boolean. Can you please explain and provide the appropriate link supporting the same. I am new to shapelib and github both , my apologies if i have asked the question in wrong forum please assist.

**Comment by rouault** [comment]
See https://github.com/OSGeo/gdal/issues/2486
