### ISSUE TITLE
Optional error message silencing

### ISSUE THREAD

**Issue by thbeu** [OSGeo/shapelib#100]
README.CMake mentions an optional shapelib.patch file for error message silencing. It is not obvious where to find this file. (I failed.)

https://github.com/OSGeo/shapelib/blob/200ae4fa2a6580e3950f06922eab52330a03c0bb/README.CMake#L20-L24

1. Should this step in the Readme file simply be removed?
1. If not, where can it be found?
1. Should error message silencing be made a configuration flag?

**Comment by rouault** [comment]
>  Should this step in the Readme file simply be removed?

likely

**Comment by thbeu** [comment]
Right. Error message silencing already is available via the error hook function.
