### ISSUE TITLE
AV Trigger: PE Has Sections Marked Executable and Writable

### ISSUE THREAD

**Issue by martinlevingtonarup** [OSGeo/shapelib#11]
Hi,

Our Cisco AMP has system has picked up the compiled version of shapelib.dll as containing a potential security threat.

The log is as follows:- 

PE Has Sections Marked Executable and Writable
Score: 24 Hits: 2
Description
Usually, code sections are marked as Readable/Non-Writable/Executable, which tells the operating system that the corresponding memory locations contain executable code and write operations should be forbidden. On the other hand, data sections are usually marked as Readable/Writable/Non-Executable, and therefore the Program Counter should never point to memory locations in the range of data sections. The presence of both the IMAGE_SCN_MEM_EXECUTE and the IMAGE_SCN_MEM_WRITE Flags could indicate the executable is packed or contains some other type of self modifying code.

Trigger
A PE containing a section that is both writable and executable will trigger this indicator.

Is it possible to update the code to remove these triggers ?

Thanks

**Comment by rouault** [comment]
- This repository only contains source code, not binary. So that should be directed to whoever provided this compiled shapelib.dll
- I strongly doubt there's self modifying code in shapelib

**Comment by martinlevingtonarup** [comment]
we compiled it from the source code in this repository.

**Comment by martinlevingtonarup** [comment]
On changing the increment linking option and this seems to have resolved the issue.

 <LinkIncremental>false</LinkIncremental>
