### ISSUE TITLE
MIT license

### ISSUE THREAD

**Issue by TheMostDiligent** [OSGeo/shapelib#12]
The library is currently licensed under GPL which makes it impossible to use in a wide range of applications. Would you consider re-licensing it under a less demanding license such as MIT?
Thank you!

**Comment by rouault** [comment]
Actually, it is released either as Lesser GPL or MIT at the choice of the licensee. See https://github.com/OSGeo/shapelib/blob/master/web/license.html

**Comment by TheMostDiligent** [comment]
Thanks, that is a great news!
Maybe it makes sense to update COPYING file to make the dual licensing situation clear. On the first look this looks like a GPL-only library.

**Comment by anatolyza** [comment]
Hi , great to see that there are several license types but it would be great if the COPYING file will note that or a LICENSE file will be added to avoid legal confusion

**Comment by thbeu** [comment]
Resolved by #64.
