### ISSUE TITLE
Unclear SHAPE_RESTORE_SHX config option

### ISSUE THREAD

**Issue by thbeu** [OSGeo/shapelib#129]
If the SHX file is missing the following error message is logged.

https://github.com/OSGeo/shapelib/blob/f948af277236f4c7caf427a38e3c54c1f4865f78/shpopen.c#L330-L335

I wonder what the SHAPE_RESTORE_SHX config option is.

**Comment by rouault** [comment]
> I wonder what the SHAPE_RESTORE_SHX config option is.

that's a GDAL concept
