### ISSUE TITLE
cmake flow doesn't create pkg-config file shapelib.pc

### ISSUE THREAD

**Issue by tsteven4** [OSGeo/shapelib#13]
however the configure flow does create shapelib.pc.

**Comment by aur-r** [comment]
The [thbeu](https://github.com/OSGeo/shapelib/pull/75/commits/b8acf5ccf3627bbba2218c0750a300c9684abdef) proposed patch seems fine and widely used, it is only missing the install destination after configure_file in CMakeLists.txt:
'+install(FILES "${SHAPELIB_PC}" DESTINATION ${CMAKE_INSTALL_LIBDIR}/pkgconfig)' to be complete, imo.

**Comment by rouault** [comment]
CC @thbeu

**Comment by thbeu** [comment]
There are #134 and #135 now as follow-ups of #75.
