### ISSUE TITLE
CMake config currently has a hard-coded `include` instead of `CMAKE_INSTALL_INCLUDEDIR`

### ISSUE THREAD

**Issue by thbeu** [OSGeo/shapelib#134]
Using absolute paths is a problem already now: The CMake config currently has a hard-coded `include` instead of `CMAKE_INSTALL_INCLUDEDIR`.

_Originally posted by @dg0yt in https://github.com/OSGeo/shapelib/pull/75#discussion_r1437764446_

**Comment by rouault** [comment]
@thbeu is this issue still opened?

**Comment by thbeu** [comment]
It's still here, but seems configurable.

https://github.com/OSGeo/shapelib/blob/2cc2975f87f89e1dab4749b1dfacfc869a258647/CMakeLists.txt#L54-L68

Note, that @dg0yt originally raised the issue.

**Comment by thbeu** [comment]
Or rather here:

https://github.com/OSGeo/shapelib/blob/2cc2975f87f89e1dab4749b1dfacfc869a258647/CMakeLists.txt#L133-L137

**Comment by thbeu** [comment]
> > Or rather here:
> > https://github.com/OSGeo/shapelib/blob/2cc2975f87f89e1dab4749b1dfacfc869a258647/CMakeLists.txt#L133-L137
> 
> And that's the INSTALL_INTERFACE which needs to be fixed.

Right. Do you know how to do?

**Comment by dg0yt** [comment]
It was part of the comment: replace `include` with `${CMAKE_INSTALL_INCLUDEDIR}`.

**Comment by thbeu** [comment]
Right. As simple as that and available via #139.

**Comment by thbeu** [comment]
> (This was initially suggested for a drive-by fix when using the same variable for the pc file.)

Thanks for reminding. I changed to `${includedir}` which we introduced in #135.
