### ISSUE TITLE
Missing DBFReadDateAttribute/DBFWriteDateAttribute

### ISSUE THREAD

**Issue by SunBlack** [OSGeo/shapelib#16]
Currently the implementation of the field `FTDate` is a bit basic:

* [ ] `DBFReadDateAttribute` is missing. Currently the best way is to use `DBF2ReadStringAttribute`  (like `QDate::fromString(DBF2ReadStringAttribute(dbfHandle, shapeId, field), "yyyyMMdd")`) as e.g. `DBF2ReadIntegerAttribute` makes it more complex to extract the year, month and date. An API like `SHP_DATE SHPAPI_CALL1(*)
DBFReadStringAttribute( DBFHandle psDBF, int iRecord, int iField )` would be nice.
* [ ] `DBFWriteDateAttribute` is missing. You need to know that you need to use `DBFWriteIntegerAttribute` or `DBFWriteDoubleAttribute`. Furthermore you need to know the format to use write it to db file (our call e.g. `attribute.getDate().toString("yyyyMMdd").toInt()`). A API like `DBFWriteDateAttribute( DBF2Handle psDBF2, int iRecord, int iField, int year, int month, int day)` would be nice, so you don't need to know the date format (or a struct instead of the 3 values)
* [ ] As you can only use numeric API to write date, it is not possible to write a proper invalid value. The date [should be in format](https://www.clicketyclick.dk/databases/xbase/format/data_types.html#DATA_TYPES) `YYYYMMDD`. E.g. in QGIS an invalid value is written as `00000000`, during this is not possible in this lib,. as it is handled as integer you can only write `0`

**Comment by thbeu** [comment]
The first two tasks are resolved by #98 (and #102).

The third task to write `"00000000"` as invalid date value is not yet resolved as it still is written as `"0"`. Let me know if this is desired.

**Comment by thbeu** [comment]
Edit: With updated #102 the third task also is fixed.
