### ISSUE TITLE
dbfcreate: allow creation of Date and Logical fields

### ISSUE THREAD

**Issue by zezzagio** [OSGeo/shapelib#167]
I'd like to be able to create Date and Logical fields with dbfcreate. Writing and reading functions are already here, it's just a matter of adding and check two other options.

I wrote changed dbfcreate and dbfadd, that seem to work; I would be happy if you consider to merge them in the master branch.

**Comment by rouault** [comment]
Please submit a pull request

**Comment by thbeu** [comment]
Can this be closed after #168 got merged?

**Comment by zezzagio** [comment]
Of course, yes.

________________________________
Da: Thomas Beutlich ***@***.***>
Inviato: Martedì, Dicembre 3, 2024 7:32:02 AM
A: OSGeo/shapelib ***@***.***>
Cc: Giovanni Zezza ***@***.***>; Author ***@***.***>
Oggetto: Re: [OSGeo/shapelib] dbfcreate: allow creation of Date and Logical fields (Issue #167)


Can this be closed after #168<https://github.com/OSGeo/shapelib/pull/168> got merged?
