### ISSUE TITLE
Unused variables should be removed

### ISSUE THREAD

**Issue by schwehr** [OSGeo/shapelib#18]
Follow up to #17 , I am going to split out tasks starting with easier / less controversial (I hope)

The first one is that there are quite a few unused variables, especially in contrib.  Most of these look like copy/paste remnants.  Others are more tricky.  e.g. defined in one place, set in one or more places, and never used.

**Comment by thbeu** [comment]
@schwehr Anything left to do here?

**Comment by schwehr** [comment]
Thanks for the ping. I thiink I got most everythin. Closing.
