### ISSUE TITLE
What are going to be the set of compilers that are supported and how old?

### ISSUE THREAD

**Issue by schwehr** [OSGeo/shapelib#23]
Initially, we need some discussion on this topic.

**Comment by neteler** [comment]
FWIW, we have a similar discussion at time in grass-dev:

- https://lists.osgeo.org/pipermail/grass-dev/2021-February/094954.html
- --> thread: https://lists.osgeo.org/pipermail/grass-dev/2021-February/thread.html#94913
- RFC forthcoming at https://trac.osgeo.org/grass/wiki/RFC

**Comment by schwehr** [comment]
@neteler Thanks!  I need to link to a few of these.  e.g.

- https://trac.osgeo.org/geos/wiki/RFC5 by @mloskot 
- https://gdal.org/development/rfc/rfc68_cplusplus11.html by @schwehr (based on geos RFC5)
- https://abseil.io/docs/cpp/platforms/platforms
- The C99 discussion with libtiff

And more, especially if they are in core libraries written in C.

And should have included this: https://en.wikipedia.org/wiki/List_of_compilers#C_compilers  But I not that table doesn't reflect necessarily newer versions of compilers.  I see a note about GCC 5.

Not sure if it should have it's own issue, but what standard should be used for shapelib.  C89 is (in my oppinion) not a good standard to stick with, so C99, C11, or?

- https://en.wikipedia.org/wiki/C_(programming_language)#History
- https://en.wikipedia.org/wiki/C99
- https://en.wikipedia.org/wiki/C11_(C_standard_revision)
- https://en.wikipedia.org/wiki/C17_(C_standard_revision)

**Comment by rouault** [comment]
I'd stick for now with what VC2015 supports (C99), since that's our baseline for GDAL. Anyway shapelib is hopefully mostly feature complete now and not necessarily in need of deep rework :-)

**Comment by schwehr** [comment]
It looks like recent autoconf setups set C99 by default.

**Comment by thbeu** [comment]
Regarding VS, shapelib requires VS2012 (when configuring with -DBUILD_TESTING=OFF) or VS2017 otherwise.

**Comment by rouault** [comment]
I think we can close this now
