### ISSUE TITLE
Cleanup endian checks

### ISSUE THREAD

**Issue by schwehr** [OSGeo/shapelib#36]
There should be only on place that checks for endian and it should be at compile time.

What do autoconf and CMake say about endianness?

- AC_C_BIGENDIAN
- TEST_BIG_ENDIAN

https://stackoverflow.com/questions/2100331/c-macro-definition-to-determine-big-endian-or-little-endian-machine

http://esr.ibiblio.org/?p=5095

**Comment by thbeu** [comment]
What is your preferred way to fix this? Is a global variable `bigEndian` required?

I used this kind of "static" endian detection whichis working for years:

https://github.com/tbeu/matio/blob/0884b80a7ee5783b6193d7e2c58f997d121d3245/src/mat4.c#L153-L173

**Comment by thbeu** [comment]
@schwehr I see that you self-assigned this issue, but nevertheless I now created #91.

**Comment by schwehr** [comment]
Awesome! I ran out of steam working on shapelib and I appreciate you doing #91.
