### ISSUE TITLE
CMake include install

### ISSUE THREAD

**Issue by thbeu** [OSGeo/shapelib#58]
The CMake install target installs the header file twice:

```
-- Installing: C:/install_dir/include/shapefil.h
-- Installing: C:/install_dir/include/shapelib/shapefil.h
```

Is this by design? If not, which is the expected location?

**Comment by thbeu** [comment]
Found it:

https://github.com/OSGeo/shapelib/blob/a6d56ee34b3e5485a504ecf9a28dfc96082a5d14/CMakeLists.txt#L248-L252

**Comment by dg0yt** [comment]
Noticed by https://github.com/microsoft/vcpkg/pull/35840#issuecomment-1868880252

> Is this by design? If not, which is the expected location?

This still needs an answer.
AFAIU `${CMAKE_INSTALL_INCLUDEDIR}/shapelib/shapefil.h` didn't exist before [CMake config was added](https://github.com/OSGeo/shapelib/commit/20ce54023f1ed9b320fe5bc06fd746d72de06892).
But the install interface just carries hard-coded `include`.
So either the second location is not "For compatibility with older installation", 
or the intented usage pattern is `#include <shapelib/shapefil.h>`,
or the intented install interface is `${CMAKE_INSTALL_INCLUDEDIR}/shapelib`.

**Comment by rouault** [comment]
CC @cffk Do you remember what your intent was ?
So the situation is that with autoconf builds, we have shapefil.h installed in $PREFIX/include
and with CMake builds now both in $PREFIX/include and $PREFIX/include/shapefil.h
Ideally we should have a uniform layout among both build systems

**Comment by cffk** [comment]
No, I don't know anything about this.  I recommend removing the second install location.
